export const demoIdentity = {
  marketplaceName: "ArgoPH Marketplace",
  userName: "Argo User",
  role: "Marketplace Administrator",
  initials: "AU",
};

export const dashboardData = {
  metrics: [
    {
      label: "GMV (30d)",
      value: "\u20b12.84M",
      change: "18.6%",
      direction: "up",
      changeTone: "positive",
      icon: "bi-graph-up-arrow",
      tone: "blue",
    },
    {
      label: "Active Sellers",
      value: "94",
      change: "6",
      direction: "up",
      changeTone: "positive",
      icon: "bi-shop",
      tone: "green",
    },
    {
      label: "Open Disputes",
      value: "3",
      change: "1 fewer",
      direction: "down",
      changeTone: "positive",
      icon: "bi-exclamation-triangle",
      tone: "rose",
    },
    {
      label: "Avg. Fulfillment Time",
      value: "5.4 hrs",
      change: "0.6h faster",
      direction: "down",
      changeTone: "positive",
      icon: "bi-clock",
      tone: "amber",
    },
  ],
  trends: {
    "Last 7 days": [
      { date: "Jul 29", value: 82000 },
      { date: "Jul 30", value: 87100 },
      { date: "Jul 31", value: 91500 },
      { date: "Aug 1", value: 96300 },
      { date: "Aug 2", value: 101800 },
      { date: "Aug 3", value: 108400 },
      { date: "Aug 4", value: 112600 },
    ],
    "Last 30 days": [
      { date: "Jul 6", value: 73100 },
      { date: "Jul 8", value: 76800 },
      { date: "Jul 10", value: 80200 },
      { date: "Jul 12", value: 77900 },
      { date: "Jul 14", value: 84600 },
      { date: "Jul 16", value: 89200 },
      { date: "Jul 18", value: 91700 },
      { date: "Jul 20", value: 88100 },
      { date: "Jul 22", value: 95400 },
      { date: "Jul 24", value: 98700 },
      { date: "Jul 26", value: 102100 },
      { date: "Jul 28", value: 99500 },
      { date: "Jul 30", value: 104800 },
      { date: "Aug 1", value: 108900 },
      { date: "Aug 4", value: 112600 },
    ],
    "Last 90 days": [
      { date: "May 6", value: 58700 },
      { date: "May 13", value: 63100 },
      { date: "May 20", value: 66900 },
      { date: "May 27", value: 71800 },
      { date: "Jun 3", value: 74100 },
      { date: "Jun 10", value: 77500 },
      { date: "Jun 17", value: 80200 },
      { date: "Jun 24", value: 83600 },
      { date: "Jul 1", value: 86200 },
      { date: "Jul 8", value: 89400 },
      { date: "Jul 15", value: 94100 },
      { date: "Jul 22", value: 97800 },
      { date: "Jul 29", value: 106500 },
    ],
  },
  trend: [
    { date: "Jul 6", value: 73100 },
    { date: "Jul 8", value: 76800 },
    { date: "Jul 10", value: 80200 },
    { date: "Jul 12", value: 77900 },
    { date: "Jul 14", value: 84600 },
    { date: "Jul 16", value: 89200 },
    { date: "Jul 18", value: 91700 },
    { date: "Jul 20", value: 88100 },
    { date: "Jul 22", value: 95400 },
    { date: "Jul 24", value: 98700 },
    { date: "Jul 26", value: 102100 },
    { date: "Jul 28", value: 99500 },
    { date: "Jul 30", value: 104800 },
    { date: "Aug 1", value: 108900 },
    { date: "Aug 4", value: 112600 },
  ],
  topSellers: [
    ["Northstar Gadgets", "\u20b1688K", 100],
    ["Luntian Living Co.", "\u20b1542K", 79],
    ["Kape Lokal Collective", "\u20b1416K", 60],
    ["Dahon Studio", "\u20b1335K", 49],
    ["Werkhaus Supply", "\u20b1261K", 38],
  ],
  orderStatus: [
    { name: "Completed", value: 63, color: "#079669" },
    { name: "Confirmed", value: 21, color: "#2563eb" },
    { name: "Active", value: 11, color: "#d97706" },
    { name: "Cancelled", value: 5, color: "#e11d48" },
  ],
  sellerMetrics: [
    { value: "94", label: "Active sellers", icon: "bi-shop", tone: "green" },
    {
      value: "4.8",
      label: "Average rating",
      icon: "bi-star-fill",
      tone: "amber",
    },
    {
      value: "94%",
      label: "On-time fulfillment",
      icon: "bi-clock",
      tone: "blue",
    },
  ],
  sellerHighlights: [
    {
      value: "\u20b1688K",
      label: "Top seller revenue (30d)",
      icon: "bi-graph-up-arrow",
      tone: "blue",
    },
    {
      value: "326",
      label: "Active listings",
      icon: "bi-box-seam",
      tone: "green",
    },
    { value: "4.8", label: "Avg. rating", icon: "bi-star-fill", tone: "amber" },
    {
      value: "1.7%",
      label: "Return rate",
      icon: "bi-arrow-return-left",
      tone: "rose",
    },
  ],
  productCategoryMix: [
    { label: "Electronics", value: 84, color: "bg-blue-600" },
    { label: "Home & Living", value: 67, color: "bg-emerald-600" },
    { label: "Food & Beverage", value: 54, color: "bg-amber-600" },
    { label: "Tools", value: 39, color: "bg-violet-500" },
    { label: "Fashion", value: 31, color: "bg-rose-600" },
    { label: "Wellness", value: 26, color: "bg-slate-500" },
  ],
  orderMetrics: [
    { value: "96", label: "Orders today", icon: "bi-cart3", tone: "blue" },
    {
      value: "2.1%",
      label: "Cancellation rate",
      icon: "bi-x-circle",
      tone: "rose",
    },
  ],
  ordersTrend: [
    { date: "Jul 6", value: 58 },
    { date: "Jul 8", value: 63 },
    { date: "Jul 10", value: 61 },
    { date: "Jul 12", value: 67 },
    { date: "Jul 14", value: 72 },
    { date: "Jul 16", value: 70 },
    { date: "Jul 18", value: 76 },
    { date: "Jul 20", value: 74 },
    { date: "Jul 22", value: 81 },
    { date: "Jul 24", value: 86 },
    { date: "Jul 26", value: 83 },
    { date: "Jul 28", value: 89 },
    { date: "Jul 30", value: 92 },
    { date: "Aug 1", value: 94 },
    { date: "Aug 4", value: 96 },
  ],
  payoutVolume: [
    { period: "May 16-31", amount: 214 },
    { period: "Jun 1-15", amount: 238 },
    { period: "Jun 16-30", amount: 257 },
    { period: "Jul 1-15", amount: 291 },
    { period: "Jul 16-31", amount: 318 },
  ],
  disputeReasons: [
    { reason: "Item not as described", value: 9 },
    { reason: "Damaged on arrival", value: 6 },
    { reason: "Wrong item shipped", value: 4 },
    { reason: "Late delivery", value: 3 },
  ],
};

export const products = [
  {
    id: "prd-001",
    name: "Nimble Air ANC Earbuds",
    sku: "NSG-AUD-210",
    seller: "Northstar Gadgets",
    category: "Electronics",
    price: "\u20b13,490.00",
    stock: 86,
    status: "Active",
    updated: "Aug 4, 2026",
  },
  {
    id: "prd-002",
    name: "Bamboo Modular Storage Set",
    sku: "LLC-HOM-044",
    seller: "Luntian Living Co.",
    category: "Home & Living",
    price: "\u20b11,280.00",
    stock: 41,
    status: "Active",
    updated: "Aug 3, 2026",
  },
  {
    id: "prd-003",
    name: "Mt. Apo Arabica Coffee Beans 500g",
    sku: "KLC-FNB-118",
    seller: "Kape Lokal Collective",
    category: "Food & Beverage",
    price: "\u20b1425.00",
    stock: 122,
    status: "Active",
    updated: "Aug 3, 2026",
  },
  {
    id: "prd-004",
    name: "Everyday Canvas Tote",
    sku: "DHS-FAS-072",
    seller: "Dahon Studio",
    category: "Fashion",
    price: "\u20b1750.00",
    stock: 58,
    status: "Active",
    updated: "Aug 2, 2026",
  },
  {
    id: "prd-005",
    name: "18V Compact Drill Driver Kit",
    sku: "WHS-TOL-019",
    seller: "Werkhaus Supply",
    category: "Tools",
    price: "\u20b14,950.00",
    stock: 17,
    status: "Pending Review",
    updated: "Aug 2, 2026",
  },
  {
    id: "prd-006",
    name: "Insulated Flask 750ml",
    sku: "LLC-HOM-053",
    seller: "Luntian Living Co.",
    category: "Home & Living",
    price: "\u20b1890.00",
    stock: 74,
    status: "Active",
    updated: "Aug 1, 2026",
  },
  {
    id: "prd-007",
    name: "Pulse Fit Activity Watch",
    sku: "NSG-WEL-031",
    seller: "Northstar Gadgets",
    category: "Wellness",
    price: "\u20b12,790.00",
    stock: 23,
    status: "Pending Review",
    updated: "Aug 1, 2026",
  },
  {
    id: "prd-008",
    name: "Seasonal Woven Market Basket",
    sku: "DHS-HOM-008",
    seller: "Dahon Studio",
    category: "Home & Living",
    price: "\u20b1650.00",
    stock: 0,
    status: "Archived",
    updated: "Jul 28, 2026",
  },
];

export const orders = [
  {
    id: "ORD-20842",
    buyer: "Mika Reyes",
    items: 2,
    total: "\u20b14,380.00",
    status: "Confirmed",
    placed: "Aug 4, 2026",
  },
  {
    id: "ORD-20841",
    buyer: "Jericho Tan",
    items: 1,
    total: "\u20b1750.00",
    status: "Active",
    placed: "Aug 4, 2026",
  },
  {
    id: "ORD-20836",
    buyer: "Paula Villanueva",
    items: 3,
    total: "\u20b15,815.00",
    status: "Completed",
    placed: "Aug 3, 2026",
  },
  {
    id: "ORD-20831",
    buyer: "Noel Garcia",
    items: 1,
    total: "\u20b14,950.00",
    status: "Completed",
    placed: "Aug 2, 2026",
  },
  {
    id: "ORD-20827",
    buyer: "Aira Flores",
    items: 2,
    total: "\u20b11,315.00",
    status: "Confirmed",
    placed: "Aug 1, 2026",
  },
  {
    id: "ORD-20819",
    buyer: "Sam Dela Cruz",
    items: 1,
    total: "\u20b12,790.00",
    status: "Cancelled",
    placed: "Jul 31, 2026",
  },
];

export const sellers = [
  {
    id: "sel-001",
    business: "Northstar Gadgets",
    owner: "Rafael Cruz",
    commission: "12%",
    rating: "4.8",
    status: "Active",
    joined: "Sep 12, 2024",
  },
  {
    id: "sel-002",
    business: "Luntian Living Co.",
    owner: "Mara Santos",
    commission: "10%",
    rating: "4.9",
    status: "Active",
    joined: "Jan 20, 2025",
  },
  {
    id: "sel-003",
    business: "Kape Lokal Collective",
    owner: "Jules Bautista",
    commission: "10%",
    rating: "4.8",
    status: "Active",
    joined: "Mar 8, 2025",
  },
  {
    id: "sel-004",
    business: "Dahon Studio",
    owner: "Inez Ramos",
    commission: "12%",
    rating: "4.7",
    status: "Active",
    joined: "Apr 17, 2025",
  },
  {
    id: "sel-005",
    business: "Werkhaus Supply",
    owner: "Leo Navarro",
    commission: "11%",
    rating: "4.6",
    status: "Active",
    joined: "Jun 2, 2025",
  },
];

export const applications = [
  {
    business: "Sining Stationery",
    owner: "Bea Mercado",
    applied: "Aug 2, 2026",
  },
  { business: "Habi Activewear", owner: "Carlo Lim", applied: "Aug 3, 2026" },
];

export const reviews = [
  {
    id: "rev-001",
    product: "Nimble Air ANC Earbuds",
    buyer: "Andrea Yu",
    rating: 5,
    comment: "Clear calls, balanced sound, and delivery arrived a day early.",
    submitted: "Aug 3, 2026",
  },
  {
    id: "rev-002",
    product: "Mt. Apo Arabica Coffee Beans 500g",
    buyer: "Victor Co",
    rating: 5,
    comment:
      "Fresh roast with a rich chocolate finish. Great value for the size.",
    submitted: "Aug 2, 2026",
  },
  {
    id: "rev-003",
    product: "Bamboo Modular Storage Set",
    buyer: "Camille Go",
    rating: 4,
    comment: "Well made and easy to assemble. One panel had a small scuff.",
    submitted: "Aug 1, 2026",
  },
];

export const flaggedReviews = [
  {
    id: "rev-004",
    product: "18V Compact Drill Driver Kit",
    buyer: "Anonymous",
    rating: 1,
    reason: "Potential competitor review pattern",
    submitted: "Aug 2, 2026",
  },
  {
    id: "rev-005",
    product: "Pulse Fit Activity Watch",
    buyer: "Nico Reyes",
    rating: 1,
    reason: "Contains offensive language",
    submitted: "Jul 30, 2026",
  },
];

export const disputes = [
  {
    id: "DSP-1048",
    order: "ORD-20836",
    raisedBy: "Paula Villanueva",
    seller: "Northstar Gadgets",
    reason: "Item not as described",
    status: "Open",
  },
  {
    id: "DSP-1045",
    order: "ORD-20831",
    raisedBy: "Noel Garcia",
    seller: "Werkhaus Supply",
    reason: "Damaged on arrival",
    status: "Investigating",
  },
  {
    id: "DSP-1042",
    order: "ORD-20827",
    raisedBy: "Aira Flores",
    seller: "Luntian Living Co.",
    reason: "Late delivery",
    status: "Open",
  },
];

export const resolvedDisputes = [
  {
    id: "DSP-1039",
    order: "ORD-20812",
    raisedBy: "Loren Chan",
    seller: "Kape Lokal Collective",
    outcome: "Refunded",
    resolved: "Jul 29, 2026",
  },
  {
    id: "DSP-1034",
    order: "ORD-20794",
    raisedBy: "Mina De Leon",
    seller: "Dahon Studio",
    outcome: "Rejected",
    resolved: "Jul 24, 2026",
  },
];

export const payouts = [
  {
    id: "pay-001",
    seller: "Luntian Living Co.",
    period: "Jul 16-31, 2026",
    amount: "\u20b174,860.00",
    status: "Pending",
    generated: "Aug 1, 2026",
  },
  {
    id: "pay-002",
    seller: "Northstar Gadgets",
    period: "Jul 16-31, 2026",
    amount: "\u20b196,420.00",
    status: "Pending",
    generated: "Aug 1, 2026",
  },
  {
    id: "pay-003",
    seller: "Kape Lokal Collective",
    period: "Jul 16-31, 2026",
    amount: "\u20b158,740.00",
    status: "Processing",
    generated: "Aug 1, 2026",
  },
  {
    id: "pay-004",
    seller: "Dahon Studio",
    period: "Jul 1-15, 2026",
    amount: "\u20b146,210.00",
    status: "Paid",
    generated: "Jul 16, 2026",
  },
];

export const categories = [
  { name: "Electronics", slug: "electronics", parent: "-", status: "Active" },
  { name: "Home & Living", slug: "home-living", parent: "-", status: "Active" },
  {
    name: "Food & Beverage",
    slug: "food-beverage",
    parent: "-",
    status: "Active",
  },
  {
    name: "Coffee & Tea",
    slug: "coffee-tea",
    parent: "Food & Beverage",
    status: "Active",
  },
  { name: "Tools", slug: "tools", parent: "-", status: "Active" },
  { name: "Fashion", slug: "fashion", parent: "-", status: "Active" },
  {
    name: "Seasonal 2025",
    slug: "seasonal-2025",
    parent: "-",
    status: "Archived",
  },
];
